
export const BlogsData = [
   
    {
      imageSrc: "/projectImages/EcommerceImage.jpg",
      category: "Tech",
      headline: "Online Store Platform",
      description: "An e-commerce platform built with React and Node.js, featuring product listings,product searching, shopping cart, and checkout.",
      link: "/projects/online-store",
      displayInto: ["Tech"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Social",
      headline: "Fitness Management App",
      description: "A fitness management web application that allows users to create, manage, and track their fitness efficiently.",
      link: "/projects/task-management-app",
      displayInto: ["Social"], 
    },
    {
      imageSrc: "/BlogImages/NewsPaper.jpg",
      category: "News",
      headline: "Global News Aggregator",
      description: "An innovative web application that aggregates and curates news from multiple sources worldwide, providing users with the latest updates and breaking news.",
      link: "/projects/global-news-aggregator",
      displayInto: ["News"],
    },
    {
      imageSrc: "/projectImages/PortfolioImage.jpg",
      category: "Social",
      headline: "Personal Portfolio Website",
      description: "A responsive personal portfolio website built using Next.js and TailwindCSS, showcasing projects and skills.",
      link: "/projects/personal-portfolio",
      displayInto: ["Social"],
    },
    {
      imageSrc: "/LatestBlogImages/ArtificialIntillegence.jpg",
      category: "Programming",
      headline: "Code Snippet Library",
      description: "A platform designed for developers to organize, and share code snippets and programming solutions.",
      link: "/projects/code-snippet-library",
      displayInto: ["Programming"],
    },        
    {
      imageSrc: "/projectImages/MobileImage.jpg",
      category: "LifeStyle",
      headline: "Music Player App",
      description: "An android music player app built with React Native, enabling users to play melodious music during workout.",
      link: "/projects/fitness-tracker-app",
      displayInto: ["LifeStyle"], 
    },
    {
      imageSrc: "/projectImages/APIImage.jpg",
      category: "Tech",
      headline: "API for Social Network",
      description: "A RESTful API developed with Node.js and Express, powering the backend of a social networking platform.",
      link: "/projects/social-network-api",
      displayInto: ["Tech"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Tech",
      headline: "Image Classification System",
      description: "A machine learning project that classifies images into multiple categories using TensorFlow and Python.",
      link: "/projects/image-classification-system",
      displayInto: ["Tech"], 
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Education",
      headline: "Content Management System",
      description: "A custom CMS developed with PHP and Laravel, allowing users to create and manage website content.",
      link: "/projects/content-management-system",
      displayInto: ["Education"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "LifeStyle",
      headline: "Healthy Recipe App",
      description: "A lifestyle application that offers a collection of healthy recipes to help users maintain a balanced diet.",
      link: "/projects/healthy-recipe-app",
      displayInto: ["LifeStyle"],
    },
    {
      imageSrc: "/projectImages/PortfolioImage.jpg",
      category: "Design",
      headline: "Portfolio Website Builder",
      description: "A sleek and customizable portfolio website builder designed for creatives to showcase their work, including templates and design tools.",
      link: "/projects/portfolio-website-builder",
      displayInto: ["Design"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Education",
      headline: "E-Learning Platform",
      description: "An interactive online learning platform that provides engaging educational content, quizzes, and progress tracking for students of all ages.",
      link: "/projects/e-learning-platform",
      displayInto: ["Education"],
    },
    {
      imageSrc: "/BlogImages/NewsPaper.jpg",
      category: "Others",
      headline: "Virtual Event Management System",
      description: "A comprehensive virtual event management system for hosting and managing online conferences, webinars, and networking events.",
      link: "/projects/virtual-event-management-system",
      displayInto: ["Others"],
    },
    {
      imageSrc: "/BlogImages/NewsPaper.jpg",
      category: "News",
      headline: "Local News Hub",
      description: "A dynamic web application that provides up-to-date news and events from local sources, offering personalized news feeds and community updates.",
      link: "/projects/local-news-hub",
      displayInto: ["News"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Programming",
      headline: "Algorithm Visualizer",
      description: "An interactive tool that visualizes various algorithms and data structures in real-time, helping developers understand complex concepts.",
      link: "/projects/algorithm-visualizer",
      displayInto: ["Programming"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "LifeStyle",
      headline: "A Meditation Guide App",
      description: "A lifestyle app designed to help users practice mindfulness and meditation with guided sessions, mood tracking, and relaxation techniques.",
      link: "/projects/mindfulness-meditation-app",
      displayInto: ["LifeStyle"],
    },
    {
      imageSrc: "/BlogImages/NewsPaper.jpg",
      category: "Design",
      headline: "Graphic Design Toolkit",
      description: "A comprehensive toolkit for graphic designers that includes vector graphics, design templates, and color palettes for creating stunning visual content.",
      link: "/projects/graphic-design-toolkit",
      displayInto: ["Design"],
    },
    {
      imageSrc: "/images/TempImage.jpg",
      category: "Others",
      headline: "Smart Home Control System",
      description: "A cutting-edge system for managing and automating smart home devices, including security systems through a user-friendly interface.",
      link: "/projects/smart-home-control-system",
      displayInto: ["Others"],
    },
    {
      imageSrc: "/BlogImages/NewsPaper.jpg",
      category: "News",
      headline: "Breaking News Alert System",
      description: "A real-time news alert system that pushes breaking news notifications to users, ensuring they stay informed about major events.",
      link: "/projects/breaking-news-alert-system",
      displayInto: ["News"],
    },
    {
      imageSrc: "/BlogImages/Programming.jpg",
      category: "Programming",
      headline: "Code Collaboration Platform",
      description: "A platform for collaborative coding that allows multiple developers to work on the same project with features for code sharing, and team communication.",
      link: "/projects/code-collaboration-platform",
      displayInto: ["Programming"],
    }                            

  ];
  